#!/usr/local/bin/fish
set branchName (git rev-parse --abbrev-ref HEAD)
if set storyId (string match -r "ENG-\d+" $branchName)
  echo "Prepending storyId $storyId to commit message...\n"
  sed -i.bak -e "1s/^/[$storyId] /" $argv[1];
else
  echo "Not a Story Branch"
end




